apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: parking
  labels:
    app: parking-test
spec:
  selector:
    matchLabels:
      app: parking-test
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: parking-test
        tier: frontend
    spec:
      containers:
      - name: parking-test
        image: parking:1.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: parking-frontend
  labels:
    app: parking-test
    tier: frontend
spec:
  type: NodePort 
  ports:
  - port: 80
  selector:
    app: parking-test
    tier: frontend
